{
    "type": "error",
    "data": "parallel transformation error",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/execution/derive_from_rows_base.py\", line 39, in execute\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/extract_entities/extract_entities.py\", line 128, in run_strategy\n    result = await strategy_exec(\n             ^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/extract_entities/strategies/graph_intelligence.py\", line 37, in run_graph_intelligence\n    llm = load_llm(\"entity_extraction\", llm_type, callbacks, cache, llm_config)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/llm/load_llm.py\", line 61, in load_llm\n    raise ValueError(msg)\nValueError: Unknown LLM type None\n",
    "source": "Unknown LLM type None",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_base_entity_graph\" in create_base_entity_graph: 1 Errors occurred while running parallel transformation, could not complete!",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/workflows/v1/subflows/create_base_entity_graph.py\", line 53, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/flows/create_base_entity_graph.py\", line 50, in create_base_entity_graph\n    entities, entity_graphs = await extract_entities(\n                              ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/extract_entities/extract_entities.py\", line 138, in extract_entities\n    results = await derive_from_rows(\n              ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/execution/derive_from_rows.py\", line 29, in derive_from_rows\n    return await derive_from_rows_asyncio(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/execution/derive_from_rows_asyncio.py\", line 41, in derive_from_rows_asyncio\n    return await derive_from_rows_base(input, transform, callbacks, gather)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/execution/derive_from_rows_base.py\", line 57, in derive_from_rows_base\n    raise VerbParallelizationError(len(errors))\ndatashaper.errors.VerbParallelizationError: 1 Errors occurred while running parallel transformation, could not complete!\n",
    "source": "1 Errors occurred while running parallel transformation, could not complete!",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/run/run.py\", line 251, in run_pipeline\n    result = await _process_workflow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/run/workflow.py\", line 89, in _process_workflow\n    result = await workflow.run(context, callbacks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/workflows/v1/subflows/create_base_entity_graph.py\", line 53, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/flows/create_base_entity_graph.py\", line 50, in create_base_entity_graph\n    entities, entity_graphs = await extract_entities(\n                              ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/extract_entities/extract_entities.py\", line 138, in extract_entities\n    results = await derive_from_rows(\n              ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/execution/derive_from_rows.py\", line 29, in derive_from_rows\n    return await derive_from_rows_asyncio(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/execution/derive_from_rows_asyncio.py\", line 41, in derive_from_rows_asyncio\n    return await derive_from_rows_base(input, transform, callbacks, gather)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/execution/derive_from_rows_base.py\", line 57, in derive_from_rows_base\n    raise VerbParallelizationError(len(errors))\ndatashaper.errors.VerbParallelizationError: 1 Errors occurred while running parallel transformation, could not complete!\n",
    "source": "1 Errors occurred while running parallel transformation, could not complete!",
    "details": null
}
