{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_final_nodes\" in create_final_nodes: \"['x', 'y'] not found in axis\"",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/workflows/v1/subflows/create_final_nodes.py\", line 36, in create_final_nodes\n    output = await create_final_nodes_flow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/flows/create_final_nodes.py\", line 48, in create_final_nodes\n    nodes_without_positions = nodes.drop(columns=[\"x\", \"y\"])\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/frame.py\", line 5581, in drop\n    return super().drop(\n           ^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4788, in drop\n    obj = obj._drop_axis(labels, axis, level=level, errors=errors)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4830, in _drop_axis\n    new_axis = axis.drop(labels, errors=errors)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/indexes/base.py\", line 7070, in drop\n    raise KeyError(f\"{labels[mask].tolist()} not found in axis\")\nKeyError: \"['x', 'y'] not found in axis\"\n",
    "source": "\"['x', 'y'] not found in axis\"",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/run/run.py\", line 251, in run_pipeline\n    result = await _process_workflow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/run/workflow.py\", line 89, in _process_workflow\n    result = await workflow.run(context, callbacks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/workflows/v1/subflows/create_final_nodes.py\", line 36, in create_final_nodes\n    output = await create_final_nodes_flow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/flows/create_final_nodes.py\", line 48, in create_final_nodes\n    nodes_without_positions = nodes.drop(columns=[\"x\", \"y\"])\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/frame.py\", line 5581, in drop\n    return super().drop(\n           ^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4788, in drop\n    obj = obj._drop_axis(labels, axis, level=level, errors=errors)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4830, in _drop_axis\n    new_axis = axis.drop(labels, errors=errors)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/indexes/base.py\", line 7070, in drop\n    raise KeyError(f\"{labels[mask].tolist()} not found in axis\")\nKeyError: \"['x', 'y'] not found in axis\"\n",
    "source": "\"['x', 'y'] not found in axis\"",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_final_nodes\" in create_final_nodes: \"['x', 'y'] not found in axis\"",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/workflows/v1/subflows/create_final_nodes.py\", line 36, in create_final_nodes\n    output = await create_final_nodes_flow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/flows/create_final_nodes.py\", line 48, in create_final_nodes\n    nodes_without_positions = nodes.drop(columns=[\"x\", \"y\"])\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/frame.py\", line 5581, in drop\n    return super().drop(\n           ^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4788, in drop\n    obj = obj._drop_axis(labels, axis, level=level, errors=errors)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4830, in _drop_axis\n    new_axis = axis.drop(labels, errors=errors)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/indexes/base.py\", line 7070, in drop\n    raise KeyError(f\"{labels[mask].tolist()} not found in axis\")\nKeyError: \"['x', 'y'] not found in axis\"\n",
    "source": "\"['x', 'y'] not found in axis\"",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/run/run.py\", line 251, in run_pipeline\n    result = await _process_workflow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/run/workflow.py\", line 89, in _process_workflow\n    result = await workflow.run(context, callbacks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/workflows/v1/subflows/create_final_nodes.py\", line 36, in create_final_nodes\n    output = await create_final_nodes_flow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/flows/create_final_nodes.py\", line 48, in create_final_nodes\n    nodes_without_positions = nodes.drop(columns=[\"x\", \"y\"])\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/frame.py\", line 5581, in drop\n    return super().drop(\n           ^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4788, in drop\n    obj = obj._drop_axis(labels, axis, level=level, errors=errors)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4830, in _drop_axis\n    new_axis = axis.drop(labels, errors=errors)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/indexes/base.py\", line 7070, in drop\n    raise KeyError(f\"{labels[mask].tolist()} not found in axis\")\nKeyError: \"['x', 'y'] not found in axis\"\n",
    "source": "\"['x', 'y'] not found in axis\"",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_final_nodes\" in create_final_nodes: \"['x', 'y'] not found in axis\"",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/workflows/v1/subflows/create_final_nodes.py\", line 36, in create_final_nodes\n    output = await create_final_nodes_flow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/flows/create_final_nodes.py\", line 48, in create_final_nodes\n    nodes_without_positions = nodes.drop(columns=[\"x\", \"y\"])\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/frame.py\", line 5581, in drop\n    return super().drop(\n           ^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4788, in drop\n    obj = obj._drop_axis(labels, axis, level=level, errors=errors)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4830, in _drop_axis\n    new_axis = axis.drop(labels, errors=errors)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/indexes/base.py\", line 7070, in drop\n    raise KeyError(f\"{labels[mask].tolist()} not found in axis\")\nKeyError: \"['x', 'y'] not found in axis\"\n",
    "source": "\"['x', 'y'] not found in axis\"",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/run/run.py\", line 251, in run_pipeline\n    result = await _process_workflow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/run/workflow.py\", line 89, in _process_workflow\n    result = await workflow.run(context, callbacks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/workflows/v1/subflows/create_final_nodes.py\", line 36, in create_final_nodes\n    output = await create_final_nodes_flow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/flows/create_final_nodes.py\", line 48, in create_final_nodes\n    nodes_without_positions = nodes.drop(columns=[\"x\", \"y\"])\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/frame.py\", line 5581, in drop\n    return super().drop(\n           ^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4788, in drop\n    obj = obj._drop_axis(labels, axis, level=level, errors=errors)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4830, in _drop_axis\n    new_axis = axis.drop(labels, errors=errors)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/indexes/base.py\", line 7070, in drop\n    raise KeyError(f\"{labels[mask].tolist()} not found in axis\")\nKeyError: \"['x', 'y'] not found in axis\"\n",
    "source": "\"['x', 'y'] not found in axis\"",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_base_entity_graph\" in create_base_entity_graph: Error code: 429 - {'error': {'message': \"No deployments available for selected model, Try again in 60 seconds. Passed model=gpt-4o. pre-call-checks=False, cooldown_list=['55df53c914eca9ce79231d49888f27df7d8ec153d21e77af85c0cfa3b01cecfc', '825042fb151c40c3689b9d78758950a38b6933eda6b2f46dd1af0efe4a82341c', 'c5dddc586b3b118a9afc2eedfe3e827243d3b99b347cda697e0dbaa1fa210b55', '327ec1698949fcd572c6001126a5924dfd57fd48568af355f1e45a63050c464a', '532475aa42fd2225d317f85c7a66451c1544597a952043d94f06e718e561ac67']\", 'type': 'None', 'param': 'None', 'code': '429'}}",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/workflows/v1/subflows/create_base_entity_graph.py\", line 53, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/flows/create_base_entity_graph.py\", line 70, in create_base_entity_graph\n    summarized = await summarize_descriptions(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/summarize_descriptions/summarize_descriptions.py\", line 136, in summarize_descriptions\n    return await get_resolved_entities(input, semaphore)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/summarize_descriptions/summarize_descriptions.py\", line 106, in get_resolved_entities\n    results = await asyncio.gather(*futures)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/summarize_descriptions/summarize_descriptions.py\", line 124, in do_summarize_descriptions\n    results = await strategy_exec(\n              ^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/summarize_descriptions/strategies.py\", line 30, in run_graph_intelligence\n    return await run_summarize_descriptions(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/summarize_descriptions/strategies.py\", line 63, in run_summarize_descriptions\n    result = await extractor(items=items, descriptions=descriptions)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/extractors/summarize/description_summary_extractor.py\", line 73, in __call__\n    result = await self._summarize_descriptions(items, descriptions)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/extractors/summarize/description_summary_extractor.py\", line 110, in _summarize_descriptions\n    result = await self._summarize_descriptions_with_llm(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/extractors/summarize/description_summary_extractor.py\", line 129, in _summarize_descriptions_with_llm\n    response = await self._llm(\n               ^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/openai/json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/openai/openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/openai/openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/tenacity/asyncio/__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/tenacity/asyncio/__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/tenacity/_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/local/python3.11-Anaconda3-2024.03-RSU-VI/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/local/python3.11-Anaconda3-2024.03-RSU-VI/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/openai/openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/openai/resources/chat/completions.py\", line 1490, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/openai/_base_client.py\", line 1838, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/openai/_base_client.py\", line 1532, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/openai/_base_client.py\", line 1633, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': \"No deployments available for selected model, Try again in 60 seconds. Passed model=gpt-4o. pre-call-checks=False, cooldown_list=['55df53c914eca9ce79231d49888f27df7d8ec153d21e77af85c0cfa3b01cecfc', '825042fb151c40c3689b9d78758950a38b6933eda6b2f46dd1af0efe4a82341c', 'c5dddc586b3b118a9afc2eedfe3e827243d3b99b347cda697e0dbaa1fa210b55', '327ec1698949fcd572c6001126a5924dfd57fd48568af355f1e45a63050c464a', '532475aa42fd2225d317f85c7a66451c1544597a952043d94f06e718e561ac67']\", 'type': 'None', 'param': 'None', 'code': '429'}}\n",
    "source": "Error code: 429 - {'error': {'message': \"No deployments available for selected model, Try again in 60 seconds. Passed model=gpt-4o. pre-call-checks=False, cooldown_list=['55df53c914eca9ce79231d49888f27df7d8ec153d21e77af85c0cfa3b01cecfc', '825042fb151c40c3689b9d78758950a38b6933eda6b2f46dd1af0efe4a82341c', 'c5dddc586b3b118a9afc2eedfe3e827243d3b99b347cda697e0dbaa1fa210b55', '327ec1698949fcd572c6001126a5924dfd57fd48568af355f1e45a63050c464a', '532475aa42fd2225d317f85c7a66451c1544597a952043d94f06e718e561ac67']\", 'type': 'None', 'param': 'None', 'code': '429'}}",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/run/run.py\", line 251, in run_pipeline\n    result = await _process_workflow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/run/workflow.py\", line 89, in _process_workflow\n    result = await workflow.run(context, callbacks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/workflows/v1/subflows/create_base_entity_graph.py\", line 53, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/flows/create_base_entity_graph.py\", line 70, in create_base_entity_graph\n    summarized = await summarize_descriptions(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/summarize_descriptions/summarize_descriptions.py\", line 136, in summarize_descriptions\n    return await get_resolved_entities(input, semaphore)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/summarize_descriptions/summarize_descriptions.py\", line 106, in get_resolved_entities\n    results = await asyncio.gather(*futures)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/summarize_descriptions/summarize_descriptions.py\", line 124, in do_summarize_descriptions\n    results = await strategy_exec(\n              ^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/summarize_descriptions/strategies.py\", line 30, in run_graph_intelligence\n    return await run_summarize_descriptions(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/summarize_descriptions/strategies.py\", line 63, in run_summarize_descriptions\n    result = await extractor(items=items, descriptions=descriptions)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/extractors/summarize/description_summary_extractor.py\", line 73, in __call__\n    result = await self._summarize_descriptions(items, descriptions)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/extractors/summarize/description_summary_extractor.py\", line 110, in _summarize_descriptions\n    result = await self._summarize_descriptions_with_llm(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/extractors/summarize/description_summary_extractor.py\", line 129, in _summarize_descriptions_with_llm\n    response = await self._llm(\n               ^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/openai/json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/openai/openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/openai/openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/tenacity/asyncio/__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/tenacity/asyncio/__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/tenacity/_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/local/python3.11-Anaconda3-2024.03-RSU-VI/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/local/python3.11-Anaconda3-2024.03-RSU-VI/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/openai/openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/openai/resources/chat/completions.py\", line 1490, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/openai/_base_client.py\", line 1838, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/openai/_base_client.py\", line 1532, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/openai/_base_client.py\", line 1633, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': \"No deployments available for selected model, Try again in 60 seconds. Passed model=gpt-4o. pre-call-checks=False, cooldown_list=['55df53c914eca9ce79231d49888f27df7d8ec153d21e77af85c0cfa3b01cecfc', '825042fb151c40c3689b9d78758950a38b6933eda6b2f46dd1af0efe4a82341c', 'c5dddc586b3b118a9afc2eedfe3e827243d3b99b347cda697e0dbaa1fa210b55', '327ec1698949fcd572c6001126a5924dfd57fd48568af355f1e45a63050c464a', '532475aa42fd2225d317f85c7a66451c1544597a952043d94f06e718e561ac67']\", 'type': 'None', 'param': 'None', 'code': '429'}}\n",
    "source": "Error code: 429 - {'error': {'message': \"No deployments available for selected model, Try again in 60 seconds. Passed model=gpt-4o. pre-call-checks=False, cooldown_list=['55df53c914eca9ce79231d49888f27df7d8ec153d21e77af85c0cfa3b01cecfc', '825042fb151c40c3689b9d78758950a38b6933eda6b2f46dd1af0efe4a82341c', 'c5dddc586b3b118a9afc2eedfe3e827243d3b99b347cda697e0dbaa1fa210b55', '327ec1698949fcd572c6001126a5924dfd57fd48568af355f1e45a63050c464a', '532475aa42fd2225d317f85c7a66451c1544597a952043d94f06e718e561ac67']\", 'type': 'None', 'param': 'None', 'code': '429'}}",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_final_nodes\" in create_final_nodes: \"['x', 'y'] not found in axis\"",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/workflows/v1/subflows/create_final_nodes.py\", line 36, in create_final_nodes\n    output = await create_final_nodes_flow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/flows/create_final_nodes.py\", line 48, in create_final_nodes\n    nodes_without_positions = nodes.drop(columns=[\"x\", \"y\"])\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/frame.py\", line 5581, in drop\n    return super().drop(\n           ^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4788, in drop\n    obj = obj._drop_axis(labels, axis, level=level, errors=errors)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4830, in _drop_axis\n    new_axis = axis.drop(labels, errors=errors)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/indexes/base.py\", line 7070, in drop\n    raise KeyError(f\"{labels[mask].tolist()} not found in axis\")\nKeyError: \"['x', 'y'] not found in axis\"\n",
    "source": "\"['x', 'y'] not found in axis\"",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/run/run.py\", line 251, in run_pipeline\n    result = await _process_workflow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/run/workflow.py\", line 89, in _process_workflow\n    result = await workflow.run(context, callbacks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/workflows/v1/subflows/create_final_nodes.py\", line 36, in create_final_nodes\n    output = await create_final_nodes_flow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/flows/create_final_nodes.py\", line 48, in create_final_nodes\n    nodes_without_positions = nodes.drop(columns=[\"x\", \"y\"])\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/frame.py\", line 5581, in drop\n    return super().drop(\n           ^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4788, in drop\n    obj = obj._drop_axis(labels, axis, level=level, errors=errors)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4830, in _drop_axis\n    new_axis = axis.drop(labels, errors=errors)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/indexes/base.py\", line 7070, in drop\n    raise KeyError(f\"{labels[mask].tolist()} not found in axis\")\nKeyError: \"['x', 'y'] not found in axis\"\n",
    "source": "\"['x', 'y'] not found in axis\"",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error in Umap",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/operations/layout_graph/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
    "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_final_nodes\" in create_final_nodes: \"['x', 'y'] not found in axis\"",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/workflows/v1/subflows/create_final_nodes.py\", line 36, in create_final_nodes\n    output = await create_final_nodes_flow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/flows/create_final_nodes.py\", line 48, in create_final_nodes\n    nodes_without_positions = nodes.drop(columns=[\"x\", \"y\"])\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/frame.py\", line 5581, in drop\n    return super().drop(\n           ^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4788, in drop\n    obj = obj._drop_axis(labels, axis, level=level, errors=errors)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4830, in _drop_axis\n    new_axis = axis.drop(labels, errors=errors)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/indexes/base.py\", line 7070, in drop\n    raise KeyError(f\"{labels[mask].tolist()} not found in axis\")\nKeyError: \"['x', 'y'] not found in axis\"\n",
    "source": "\"['x', 'y'] not found in axis\"",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/run/run.py\", line 251, in run_pipeline\n    result = await _process_workflow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/run/workflow.py\", line 89, in _process_workflow\n    result = await workflow.run(context, callbacks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/workflows/v1/subflows/create_final_nodes.py\", line 36, in create_final_nodes\n    output = await create_final_nodes_flow(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/flows/create_final_nodes.py\", line 48, in create_final_nodes\n    nodes_without_positions = nodes.drop(columns=[\"x\", \"y\"])\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/frame.py\", line 5581, in drop\n    return super().drop(\n           ^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4788, in drop\n    obj = obj._drop_axis(labels, axis, level=level, errors=errors)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/generic.py\", line 4830, in _drop_axis\n    new_axis = axis.drop(labels, errors=errors)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/pandas/core/indexes/base.py\", line 7070, in drop\n    raise KeyError(f\"{labels[mask].tolist()} not found in axis\")\nKeyError: \"['x', 'y'] not found in axis\"\n",
    "source": "\"['x', 'y'] not found in axis\"",
    "details": null
}
{
    "type": "error",
    "data": "Community Report Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/index/graph/extractors/community_reports/community_reports_extractor.py\", line 58, in __call__\n    await self._llm(\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/openai/json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/openai/openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/openai/openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/tenacity/asyncio/__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/tenacity/asyncio/__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/tenacity/_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 398, in <lambda>\n    self._add_action_func(lambda rs: rs.outcome.result())\n                                     ^^^^^^^^^^^^^^^^^^^\n  File \"/local/python3.11-Anaconda3-2024.03-RSU-VI/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/local/python3.11-Anaconda3-2024.03-RSU-VI/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/base/base_llm.py\", line 49, in __call__\n    return await self._invoke_json(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/proj/ciptmp/ix05ogym/myenv/lib/python3.11/site-packages/graphrag/llm/openai/openai_chat_llm.py\", line 90, in _invoke_json\n    raise RuntimeError(error_msg)\nRuntimeError: Failed to generate valid JSON output - Faulty JSON: {}\n",
    "source": "Failed to generate valid JSON output - Faulty JSON: {}",
    "details": null
}
